env: 
  browser: true
  es2021: true
  node: true
extends: 
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:react/recommended"
parserOptions: 
  ecmaFeatures: 
    jsx: true
  ecmaVersion: 12
  emitWarning: true
  jsxPragma: null // for @typescript/eslint-parser
  sourceType: module
rules:
  "@typescript-eslint/no-unused-vars":
    - off
  "@typescript-eslint/no-empty-function":
    - off
  array-bracket-spacing: 
    - error
    - always
    - arraysInArrays: false
      objectsInArrays: true
      singleValue: false
  comma-dangle: 
    - error
    - always-multiline
  eol-last: 
    - error
    - always
  indent: 
    - warn
    - 2
  jsx-quotes: 
    - error
    - prefer-single
  key-spacing: 
    - error
    - afterColon: true
      beforeColon: false
      mode: minimum
  linebreak-style: 
    - error
    - unix
  multiline-comment-style: 
    - error
    - separate-lines
  no-unused-vars: 
    - off
  object-curly-spacing: 
    - error
    - always
    - arraysInObjects: true
      objectsInObjects: false
  quotes: 
    - warn
    - single
  react/display-name: 
    - warn
  react/jsx-filename-extension: 
    - 1
    - extensions: 
        - .js
        - .jsx
        - .ts
        - .tsx
  react/jsx-uses-vars: warn
  react/prop-types: off
  react/react-in-jsx-scope: off
  semi: 
    - warn
    - always
  space-infix-ops: 
    - error
